//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairAndNailData.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Popust> Popust { get; set; }
        public virtual DbSet<Racun> Racun { get; set; }
        public virtual DbSet<Racun_sadrzi_usluge> Racun_sadrzi_usluge { get; set; }
        public virtual DbSet<Rezervacija> Rezervacija { get; set; }
        public virtual DbSet<Salon> Salon { get; set; }
        public virtual DbSet<Smjena> Smjena { get; set; }
        public virtual DbSet<Termin> Termin { get; set; }
        public virtual DbSet<Tip_korisnika> Tip_korisnika { get; set; }
        public virtual DbSet<Usluga> Usluga { get; set; }
        public virtual DbSet<Vrsta_usluge> Vrsta_usluge { get; set; }
        public virtual DbSet<Tvrtka> Tvrtka { get; set; }
        public virtual DbSet<Uloga> Uloga { get; set; }
    }
}
