//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairAndNailData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Racun()
        {
            this.Racun_sadrzi_usluge = new HashSet<Racun_sadrzi_usluge>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> Iznos { get; set; }
        public int Korisnik_id { get; set; }
        public int Salon_id { get; set; }
        public int Popust_id { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Popust Popust { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun_sadrzi_usluge> Racun_sadrzi_usluge { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
