//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairAndNailData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Status { get; set; }
        public int Korisnik_id { get; set; }
        public int Termin_id { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Termin Termin { get; set; }
    }
}
